### ISSUE TITLE
Adding "loo" criterion with add_criterion and moment_match=TRUE is failing even when save_pars(all=TRUE) was set during model fit

### ISSUE THREAD

**Issue by eipi10** [stan-dev/loo#222] opened 2023-04-11 16:23 UTC
I'm fitting ordinal regression models using brms, but I'm getting an error when I try to add a loo criterion with `moment_match=TRUE`, even though I fit the model with `save_pars(all=TRUE)`. The error message is `Error in if (quantities_i$ki < ki) { : missing value where TRUE/FALSE needed.` 

I've created some fake data with a similar structure to my real data (but with far fewer observations and with only a few of the columns that are in my real data) in order to reproduce the error. Here is a link to the sample data:
 
[sample-data.csv](https://github.com/paul-buerkner/brms/files/11181049/sample-data.csv)

Even this sample has a relatively large number of rows (20,591) as I wasn't able to reproduce the error with smaller data frames. 

Reproducible code is below, along with the warnings and error messages. 

(FYI, I [posted a question](https://discourse.mc-stan.org/t/add-criterion-with-moment-match-true-failing-even-when-save-pars-all-true-was-set-during-model-fit/30956) about this on the Stan Forum several days ago but didn't get an answer. I also originally posted this issue on the [`brms` repo](https://github.com/paul-buerkner/brms/issues/1479), but Paul pointed out that the error is coming from `loo` and asked me to post the issue here.)

```
# Session Info
# Macbook Pro M1 Max, Ventura 13.2.1
# R 4.2.3
# brms 2.19.0
# rstan 2.26.13
# stanheaders 2.26.13
# cmdstanr 0.5.2
# cmdstan 2.31.0
# loo 2.6.0

library(tidyverse)
library(brms)

dd = read.csv("sample-data.csv") %>%
  mutate(student.id = factor(student.id),
         instructor.id = factor(instructor.id),
         grade = ordered(grade, levels=c("F","D-","D","D+","C-","C","C+","B-","B","B+","A-","A")))

form = grade ~ incoming.gpa + learning.mode + instructor.rank +
  (1|instructor.id) + (1|student.id)

priors = c(prior(normal(0,0.5), class="b"),
           prior(normal(0,1), class="b", coef="incoming.gpa"))

mod1 = brm(data=dd, 
           file="models/mod1",
           formula=form, 
           family=cumulative(link="logit", threshold="flexible"),
           prior=priors,
           chains=3, cores=3, threads=threading(3),
           backend="cmdstanr",
           sample_prior=TRUE,
           save_pars=save_pars(all=TRUE))

mod1 = add_criterion(mod1, criterion="loo", moment_match=FALSE)
# Automatically saving the model object in 'models/mod1.rds'
# Warning message:
# Found 256 observations with a pareto_k > 0.7 in model 'mod1'. It is recommended to set 'moment_match = TRUE' in order to perform moment matching for problematic observations. 

mod1a = mod1
saveRDS(mod1a, "models/mod1a.rds")

mod1a = add_criterion(mod1a, criterion="loo", moment_match=TRUE, overwrite=TRUE)
# Recompiling the model with 'rstan'
# Recompilation done
# Error in if (quantities_i$ki < ki) { : 
#   missing value where TRUE/FALSE needed
# Error: Moment matching failed. Perhaps you did not set 'save_pars = save_pars(all = TRUE)' when fitting your model? If you are running moment matching on another machine than the one used to fit the model, you may need to set recompile = TRUE.
```

**Comment by eipi10** [comment] 2023-04-25 17:36
Just checking in on this issue. Is there a way to determine whether this is a bug in `loo` or a problem specific to my model that I could fix?

**Comment by jgabry** [comment] 2023-06-21 21:43
Sorry for the slow reply! Tagging @topipa since he is most familiar with the moment matching code.

**Comment by topipa** [comment] 2023-06-25 18:31
Thank you for reporting the issue! I was able to reproduce it, and it seems like a bug in `loo`. The error appeared because the `gpdfit` function returned `NA` for Pareto k. This happened because the tail of importance weights had 29 almost zero values and only a single importance weight was 1.

In `gpdfit`, there is a [check](https://github.com/stan-dev/loo/blob/2fec3c006e52dca504f27e7870d121706272a567/R/gpdfit.R#L52)
```
if (is.nan(k)) {
  k <- Inf
}
```
but because in this case `k` is `NA` and not `NaN`, `is.nan` is false and k is kept as `NA`. I wonder if this should be changed to `is.na(k)` which would make k `Inf` if it's either `NaN` or `NA`. This would fix the error. What do you think @jgabry ?

**Comment by jgabry** [comment] 2023-06-27 16:07
> I wonder if this should be changed to `is.na(k)` which would make k `Inf` if it's either `NaN` or `NA`. This would fix the error. What do you think @jgabry ?

Yeah, good idea!

**Comment by jgabry** [comment] 2023-07-03 17:00
@eipi10 I just merged @topipa's pull request to address this. Thanks for bringing this to our attention.

**Comment by eipi10** [comment] 2023-07-04 06:54
I installed the development version of 'loo' and ran my reproducible example. `add_criterion` worked without moment matching. However, RStudio crashed ("R session aborted") when I ran `mod1 = add_criterion(mod1, criterion="loo", moment_match=TRUE)`. RStudio also crashed when I ran `loo(mod1, moment_match=TRUE)`. 

To see if this was an RStudio issue, I opened R directly and ran `mod1 = add_criterion(mod1, criterion="loo", moment_match=TRUE)` in the R console. This threw an error, but printed the error traceback to the console (see below). I can't tell whether this is a bug in `loo` or a problem with my system configuration. Are you able to determine what's causing the error?

```
Recompiling the model with 'rstan'
Recompilation done

 *** caught segfault ***
address 0x80, cause 'invalid permissions'

Traceback:
 1: .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: 0x6000004a1980>,     dll = list(name = "Rcpp", path = "/Users/jschwartz/Library/R/arm64/4.3/library/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, handle = <pointer: 0x8f5e4e20>,         info = <pointer: 0x6000021e9560>), numParameters = -1L),     <pointer: 0x6000039de200>, <pointer: 0x6000003f0cc0>, .pointer,     ...)
 2: object@.MISC$stan_fit_instance$log_prob(upars, adjust_transform,     gradient)
 3: .local(object, ...)
 4: FUN(newX[, i], ...)
 5: FUN(newX[, i], ...)
 6: apply(upars, 1, rstan::log_prob, object = x, adjust_transform = TRUE,     gradient = FALSE)
 7: log_prob_upars_stanfit(x$fit, upars = upars, ...)
 8: log_prob_upars(x, upars = upars, ...)
 9: loo::loo_moment_match.default(x, loo = loo, post_draws = as.matrix,     log_lik_i = .log_lik_i, unconstrain_pars = .unconstrain_pars,     log_prob_upars = .log_prob_upars, log_lik_i_upars = .log_lik_i_upars,     k_threshold = k_threshold, newdata = newdata, resp = resp,     ...)
10: doTryCatch(return(expr), name, parentenv, handler)
11: tryCatchOne(expr, names, parentenv, handlers[[1L]])
12: tryCatchList(expr, classes, parentenv, handlers)
13: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call, nlines = 1L)        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
14: try(loo::loo_moment_match.default(x, loo = loo, post_draws = as.matrix,     log_lik_i = .log_lik_i, unconstrain_pars = .unconstrain_pars,     log_prob_upars = .log_prob_upars, log_lik_i_upars = .log_lik_i_upars,     k_threshold = k_threshold, newdata = newdata, resp = resp,     ...))
15: loo_moment_match.brmsfit(x = .x1, loo = .x2, newdata = .x3, resp = .x4,     k_threshold = .x5, check = .x6)
16: loo_moment_match(x = .x1, loo = .x2, newdata = .x3, resp = .x4,     k_threshold = .x5, check = .x6)
17: eval(expr, envir, ...)
18: eval(expr, envir, ...)
19: eval2(call, envir = args, enclos = envir)
20: do_call("loo_moment_match", moment_match_args)
21: .loo(x = .x1, newdata = .x2, resp = .x3, model_name = .x4, pointwise = .x5,     k_threshold = .x6, save_psis = .x7, moment_match = .x8, reloo = .x9,     moment_match_args = .x10, reloo_args = .x11)
22: eval(expr, envir, ...)
23: eval(expr, envir, ...)
24: eval2(call, envir = args, enclos = envir)
25: do_call(paste0(".", criterion), args)
26: .fun(criterion = .x1, pointwise = .x2, resp = .x3, k_threshold = .x4,     save_psis = .x5, moment_match = .x6, reloo = .x7, moment_match_args = .x8,     reloo_args = .x9, x = .x10, model_name = .x11, use_stored = .x12)
27: eval(expr, envir, ...)
28: eval(expr, envir, ...)
29: eval2(call, envir = args, enclos = envir)
30: do_call(compute_loo, args)
31: .fun(models = .x1, criterion = .x2, pointwise = .x3, compare = .x4,     resp = .x5, k_threshold = .x6, save_psis = .x7, moment_match = .x8,     reloo = .x9, moment_match_args = .x10, reloo_args = .x11)
32: eval(expr, envir, ...)
33: eval(expr, envir, ...)
34: eval2(call, envir = args, enclos = envir)
35: do_call(compute_loolist, args)
36: loo.brmsfit(.x1, moment_match = .x2, model_names = .x3)
37: loo(.x1, moment_match = .x2, model_names = .x3)
38: eval(expr, envir, ...)
39: eval(expr, envir, ...)
40: eval2(call, envir = args, enclos = envir)
41: do_call(fun, args)
42: add_criterion.brmsfit(mod1, criterion = "loo", moment_match = TRUE)
43: add_criterion(mod1, criterion = "loo", moment_match = TRUE)
```

**Comment by topipa** [comment] 2023-07-04 20:22
@eipi10 Often issues like this are fixed by reinstalling stan related packages. This error seems to come from `rstan`, so I would try to reinstall that first and see if it helps. If not, also reinstalling R might help. There are several similar cases reported in Stan discourse, for example [this one](https://discourse.mc-stan.org/t/segfault-with-bridgesampling/24372).

**Comment by eipi10** [comment] 2023-07-05 17:02
I reinstalled everything and was able to get moment matching to work, but I just want to confirm whether moment matching is working as expected. 
* Without moment matching, `loo` takes about 25 seconds with 4 cores and 31 seconds with 1 core. With moment matching, `loo` takes about 2.7 *hours* with 4 cores.
* The `loo` results are exactly the same with and without moment matching: 254 observations out of 20,591 with pareto-k in $(0.7, 1.0]$.  
* With moment matching, `loo` used up all available RAM (about 60GB out of 64BG, the rest was being used by the system). In fact, when I tried to use more than 4 cores, I got a "system has run out of application memory. Please close some applications" warning. 
Are you getting the same results when you run the reproducible example? Is this expected?

**Comment by topipa** [comment] 2023-07-05 21:09
@eipi10 I'm glad you were able to run it successfully! What you describe sounds expected for the most part:

1. With such a big dataset & model, moment matching is expected to be much slower than regular loo. But I believe doing leave-one-out cross-validation by fitting the model 254 times is even slower, right?
2. It's unfortunate to hear that moment matching was not able to lower any of the pareto k values. While it's unfortunate, it is somewhat expected in a model with so many parameters (arising from the hierarchical components). Perhaps we should manage expectations better somehow regarding the limited benefit in high dimensions.
3. I have not encountered issues with memory use, but it's entirely possible that there is room for improvement in this area. I'm happy to hear if you have some suggestions on this.

**Comment by eipi10** [comment] 2023-07-06 03:32
@topipa, regarding 1. and 2.: I was hoping your answer would be that moment matching should really be much faster and that it should usually vastly improve loo results. Alas, reality isn't always so generous. Nevertheless, the reproducible example is somewhat artificial. My real data is private and I was just trying to create fake data that would generate the same error. Hopefully, I'll be able to do better with my real data and real model. (FYI, moment matching was much faster than full model refits. Fitting the example model took about 730 seconds, so 254 refits would be much more expensive than the 9,800 seconds taken by `loo` with moment matching.) Regarding 3., I'm not sure why the memory usage was so large, but if I come up with any insights, I will share them here. 

In any case, than you very much for resolving this issue!

**Comment by avehtari** [comment] 2023-11-29 17:18
It seems like this issue has been resolved and could be closed? @eipi10 can you confirm?

**Comment by eipi10** [comment] 2023-11-29 17:31
Yes, confirmed. Thanks!

**Closed** 2023-11-29 17:52 UTC
