### ISSUE TITLE
loo on rstanarm object failing

### ISSUE THREAD

**Issue by Athanasiamo** [stan-dev/loo#57] opened 2018-02-20 10:18 UTC
Not actually sure if this is a loo or rstanarm issue. 

Trying to run loo on output from stan_glmer (I have used the data option). This has run successfully before (R.3.3.2), and I could easily compare the models.
I've been rerunning analyses for a revision, and have also upgrades R and rstanarm and loo, but now I can't get loo running on the rstanarm objects.

Where **Treatment** is the output from running stan_glmer, I get the following error:

```{r}
Treatment = stan_glmer (Acc~  Treatment + (Treatment|ID),
                           adapt_delta=.99, init_r = 0.1,
                           data=df, family='binomial')

LOO = loo(Treatment, cores=4)

Error in vapply(out, "[[", 2L, FUN.VALUE = numeric(1)) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 0
```

**Comment by avehtari** [comment] 2018-02-20 21:40
Could you report exact package versions for loo and rstanarm? You can pick them, for example, from the output of `sessionInfo()`? Can you check that your data has not changed?

**Comment by Athanasiamo** [comment] 2018-02-22 07:10
rstanarm: 2.17.3
loo: 1.1.0

**Comment by avehtari** [comment] 2018-02-22 15:36
> rstanarm: 2.17.3
> loo: 1.1.0
so these are the problematic versions? Do you remember which versions did work?

Can you try using loo version in github? (installing loo from github is quite easy compared to what installing rstanarm from github may require)

@jgabry do you have any ideas?

**Comment by jgabry** [comment] 2018-02-23 05:49
Hey @Athanasiamo sorry you’re getting this error.

Do you have code that reproduces this error? I’ll see if I can figure this
out, but that would be super helpful.

Also, if you can, when you fit both models again in a fresh session using
the same packages do you still get the error?

**Comment by jgabry** [comment] 2018-02-23 17:53
Ok thanks! I’ll look into this and hopefully get it sorted out.

**Comment by jgabry** [comment] 2018-02-23 18:12
Hmm, I'm not able to reproduce this error. Using loo v1.1.0 and rstanarm v2.17.3 (same versions as you have installed),  and with your example data I get: 

```
library(readr)
loo_data_fail <- read_delim("~/Downloads/loo_data_fail.tsv", "\t", escape_double = FALSE, trim_ws = TRUE)

library(rstanarm)
testE <- stan_lmer(Value ~  Group + (1|ID),  data=loo_data_fail)
loo(testE)

Computed from 4000 by 93 log-likelihood matrix

         Estimate   SE
elpd_loo   -103.6  6.7
p_loo         6.2  0.9
looic       207.3 13.5

Pareto k diagnostic values:
                         Count  Pct 
(-Inf, 0.5]   (good)     92    98.9%
 (0.5, 0.7]   (ok)        1     1.1%
   (0.7, 1]   (bad)       0     0.0%
   (1, Inf)   (very bad)  0     0.0%

All Pareto k estimates are ok (k < 0.7)
See help('pareto-k-diagnostic') for details.
```

So I'm not sure why the same thing is failing for you. I did notice that you had used `loo::loo(testE)`, which should be ok, but what happens if you use `rstanarm::loo(testE)` instead? They _should_ both work (they do for me) but if one works for you and not the other that would give me useful information for tracking this down.

**Comment by Athanasiamo** [comment] 2018-02-24 19:42
This is very odd. I grabbed github loo to my cluster, ran my analyses, with loo, and now it worked. Still have some malfunction on my local system, that I cannot fathom, because the cluster is running the same locale, R, rstanarm and loo versions!

I just realised something, and tried running loo outside of RStudio, as it is more or less the only difference between me and the cluster (other than OS). and lo and behold! I can run loo locally in the terminal, but in RStudio... 

I updated to RStudio 1.1.423 from 1.1.414, but that didn't help :/

**Comment by jgabry** [comment] 2018-02-24 23:25
Yeah this is super weird. And must be annoying.

It should definitely work in rstudio. It shouldn’t matter at all. Does it
always error in rstudio or just for some models?

And does

loo::loo(log_lik(rstanarm_model))

give the same error as

rstanarm::loo(rstanarm_model)

or is it different?

**Comment by jgabry** [comment] 2018-02-26 18:06
> loo::loo(log_lik(rstanarm_model)) worked! It's running without that error now.

Great! Until I get this sorted out I guess just use that method if it's working. 

> Why would that work rather than running it directly?

So it's a bit convoluted, but here's what's going on: `loo::loo` and `rstanarm::loo` both point to exactly the same `loo` function in the loo package. That `loo` function is a generic with methods for log-likelihood matrices (`loo.matrix`) and for log-likelihood functions (`loo.function`), and, when rstanarm is available, for stanreg objects (`loo.stanreg`). The latter is just a wrapper around `loo.function` that first gets the needed info from the stanreg object and then passes it to the `loo.function` in the loo package. So when you call `loo(fit)` and `fit` is a stanreg object, it actually works internally like this:

`loo(fit)` -> `loo.stanreg(fit)` -> `loo.function(loglik_function_and_data_taken_from_fit)`

However, when you use `log_lik(fit)` it results in `loo.matrix` being used instead of `loo.function`:

`loo(log_lik(fit))` -> `loo.matrix(log_lik_matrix_from_fit)`

So if you get an error when using `loo(fit)` but not when using `loo(log_lik(fit))` it suggests to me that this is actually an issue with how rstanarm is preparing stuff for `loo.function`. 

Anyway, that's probably more detail that you wanted! But this does narrow down where to look for the problem.

**Comment by jgabry** [comment] 2018-03-01 00:37
I’m also hoping this will be resolved by the release of the next rstanarm
and loo updates. We’ll have those out within the next few weeks. I’m glad
there’s at least a working method for you to use in the meantime.

**Comment by Athanasiamo** [comment] 2018-03-01 09:33
the level of detail is great! Gives me a better impression of what is happening and why one works and not the other.

Just so it's said, I have just also encountered another issue with a completely different package, which seems very specific to me and noone else. I'm not sure, but apparently somewhere in my system things are not what they should. Which is frustrating.

**Comment by avehtari** [comment] 2018-03-01 09:37
>  I'm not sure, but apparently somewhere in my system things are not what they should. Which is frustrating.

I had once also strange problems which didn't go away by upgrading and it turned out that somehow there was old installation in read-only directory and upgrading packages seemed to work, but still when running it did use something from that old place. I uninstalled all R software, deleted remaining directories and re-installed everything from scratch.

**Comment by Athanasiamo** [comment] 2018-03-01 09:40
> I had once also strange problems which didn't go away by upgrading

This makes me feel a little better. At least I'm not the n00b who broke R :P

**Comment by jgabry** [comment] 2018-05-02 01:04
Im going to close this for now, but we can definitely reopen if this problem returns

**Closed by jgabry** 2018-05-02 01:04 UTC

**Comment by Athanasiamo** [comment] 2018-05-14 05:39
I dont meant to reopen, just want to apologise for not following up! Due to some unforseen issues at work I needed to let this project wait for a little. I'll let you know if my problem persists after updating and testing again.
